Disable kdump for %arm - boo#1203888
yast/skelcd-control-MicroOS pull request #61
Opened 2022-09-29 13:05 UTC by ggardet

2022-10-05 07:32 UTC, ancorgs approved these changes
LGTM

2022-10-05 07:38 UTC, teclator commented
I guess we should ensure these changes do not collide with the current proposal as kdump is enabled by default 

- see https://github.com/yast/skelcd-control-MicroOS/blob/master/control/control.MicroOS.xml#L73

2022-10-05 07:41 UTC, ggardet commented
> I guess we should ensure these changes do not collide with the current proposal as kdump is enabled by default
> 
> * see https://github.com/yast/skelcd-control-MicroOS/blob/master/control/control.MicroOS.xml#L73

Not sure how to add a condition on the architecture in this file. Any suggestion?

2022-10-05 07:49 UTC, ancorgs commented
> I guess we should ensure these changes do not collide with the current proposal as kdump is enabled by default

I would certainly expect that to be a problem. I overlooked it in my LGTM. Sorry.

To be honest, I assumed this was manually tested before submitting it (I should have asked). 

The bad news is that I merged the corresponding PR for Factory (https://github.com/yast/skelcd-control-openSUSE/pull/256). Although maybe that is not a problem since I think kdump is not part of the installer proposal in Tumbleweed.

2022-10-05 07:58 UTC, ggardet commented
> > I guess we should ensure these changes do not collide with the current proposal as kdump is enabled by default
> 
> I would certainly expect that to be a problem. I overlooked it in my LGTM. Sorry.
> 
> To be honest, I assumed this was manually tested before submitting it (I should have asked).
> 
> The bad news is that I merged the corresponding PR for Factory ([yast/skelcd-control-openSUSE#256](https://github.com/yast/skelcd-control-openSUSE/pull/256)). Although maybe that is not a problem since I think kdump is not part of the installer proposal in Tumbleweed.

That's good news, it will be a good test. This is currently broken anyway, so not a big deal.

2022-10-10 07:37 UTC, teclator requested changes
Please add version bump

2022-10-10 07:38 UTC, teclator commented on package/skelcd-control-MicroOS.changes
> +- Disable kdump for %arm - boo#1203888
```suggestion
- Disable kdump for %arm - boo#1203888
- 20221010
```

2022-10-10 07:40 UTC, teclator approved these changes

2022-10-10 07:42 UTC, merged