Fix syntax of additional_dialogs (boo#1202852)
yast/skelcd-control-MicroOS pull request #63
Opened 2022-10-26 09:24 UTC by Vogtinator

Multiple modules are separated by commas.

https://bugzilla.suse.com/show_bug.cgi?id=1202852

YaST internal error is gone after this change.

2022-10-26 14:21 UTC, dirkmueller commented
according to the comment in https://github.com/yast/skelcd-control-MicroOS/pull/62 it appears also a version update in the spec file is needed?

2022-10-26 14:25 UTC, Vogtinator commented
IMO that needs to be done after accepting PRs. If PRs always defined their version numbers that's just a nightmare.

2022-10-26 14:41 UTC, sysrich commented
@dirkmueller is right.. this repo and the CI behinds it expects the PR to have the spec changes.

2022-10-26 14:45 UTC, Vogtinator commented
Sigh.

2022-10-26 14:47 UTC, Vogtinator commented
Does it really expect the *PR* to have the spec change or can it just be commited to master directly? If so, that would already make the workflow 99% less painful if whoever merges the PR just does `rake version:bump`.

2022-10-26 15:06 UTC, joseivanlopez requested changes
Please, add changelog entry and bump version. Thanks!

2022-10-26 15:21 UTC, sysrich commented
> Does it really expect the _PR_ to have the spec change or can it just be commited to master directly? If so, that would already make the workflow 99% less painful if whoever merges the PR just does `rake version:bump`.

Yup it does, just like all the github.com/yast repos

I don't make the rules, I just follow and respect them, they must make sense for the folk who own the repo :)

2022-10-27 06:45 UTC, Vogtinator commented
> Please, add changelog entry and bump version. Thanks!

Done.

> I don't make the rules, I just follow and respect them, they must make sense for the folk who own the repo :)

Maybe at some point they did, but at this point I hope it's just a left over tradition and they know better meanwhile...

2022-10-27 08:14 UTC, joseivanlopez approved these changes
LGTM

2022-10-27 08:14 UTC, merged

2022-10-27 08:22 UTC, joseivanlopez commented
> Maybe at some point they did, but at this point I hope it's just a left over tradition and they know better meanwhile...

Almost all repos developed by YaST team follow the same CI rules: a  changelog entry with a bug/feature reference is required, as well as a new version. Otherwise the package is not submitted to OBS/IBS. Other repos like libstorage-ng or installation-images (both are not owned by YaST team anymore) follow a different approach. For them, the version bump and changelog entry are automatically done as part of the CI process. Although that has some advantages (e.g., makes the contributions easier and also avoids conflicts with PRs developed in parallel), it also has some drawbacks (e.g., you lose the control about when the version is bumped and about the content of the changelog).

For now, the manual approach is more suitable for us. Thanks!

2022-10-27 08:27 UTC, Vogtinator commented
>  Although that has some advantages (e.g., makes the contributions easier and also avoids conflicts with PRs developed in parallel), it also has some drawbacks (e.g., you lose the control about when the version is bumped and about the content of the changelog).
>
> For now, the manual approach is more suitable for us. Thanks!

IMO the design of having PRs with their own version bumps and changelog entries is just totally broken as it makes it impossible to have multiple PRs pending at the same time - they'll always conflict. It's also something which is trivial to automate anyway, as the other repos show.

What I suggest is to have the version bump and changelog generation (based on commits) handled by a manually trigggered GitHub action, which can be done by whoever merges a PR. This can then also trigger the SR on OBS.

2022-10-27 09:14 UTC, joseivanlopez commented
Yes, this is a recurrent topic in our team. We will try to find a better solution (if time permits), see https://trello.com/c/fIPmMzoJ/5271-create-changlog-entry-and-version-bump-automatically. Thanks for your feedback guys!

2022-10-27 09:16 UTC, Vogtinator commented
> Yes, this is a recurrent topic in our team. We will try to find a better solution (if time permits), see https://trello.com/c/fIPmMzoJ/5271-create-changlog-entry-and-version-bump-automatically. Thanks for your feedback guys!

I don't have access to that trello board, but let's avoid opening that can of worms as well ;-)